name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose --release
    - name: UPX
      uses: crazy-max/ghaction-upx@v1.4.0
      with:
        args: --best --lzma
        files: target/x86_64-pc-windows-msvc/release/create-performance-task.exe
    - name: Upload
      uses: actions/upload-artifact@v3.0.0
      with:
        path: target/x86_64-pc-windows-msvc/release/create-performance-task.exe
